### ISSUE TITLE
Light Missiles causing failure to load 

### ISSUE THREAD

**Issue by Conan547** [dickloraine/dragon-rampant-builder#1]
Any list containing light Missiles as a unit will not load from within the app

**Comment by dickloraine** [comment]
Thanks for the report.
I can't reproduce the problem, it works for me on Firefox and Chrome and on Android. Can you answer the following questions, so that I can try to reproduce the issue?

1. What are the exact steps you took, that lead to the error?
2. Which browser do you use?
3. Do you use the app as an installed web app? If yes on what kind of device (android, ios etc.)?

**Comment by Conan547** [comment]
No problem, that's very strange!

1. I made a new list with several units, including light missiles with the sharpshooter upgrade, then saved the list. When attempting to load the list again, I get a blank white screen and nothing else.
2. I'm using chrome on android 
3. I don't currently have it downloaded, honestly I wasn't aware that was an option! 

Hope these answers help.

**Comment by dickloraine** [comment]
Strange. For me it just works. Can you try opening the app in an incognito window of chrome and see if it works there? In an incognito window chrome makes a new database and it is not persistent. If it works in the incognito mode, then the problem is most likely either a corrupted database, service worker or some chrome plugin. If the problem persists in the incognito mode, most likely something is wrong in the app itself.

To 3: On Android you should get a little popup from chrome that asks, if you want to add the app to the homescreen. That "installs" the app (it just means you have an icon and it starts in a browser window without the adressbar etc.).

**Comment by Conan547** [comment]
It works incognito, how strange! Is there something I can do to fix it on my end?

**Comment by dickloraine** [comment]
Yes, you could try to delete the data. Then you would start fresh and hopefully it was some coruuption in the saved data. There are two ways. I think the easiest is: 
1. Install the app (either use the popup, or if it doesn't appear, click on the hamburger menu in chrome and there should be an option to install the app. 
2.  Now find the app on your phone and uninstall it.
3. Now the next time you go to the website, you have a new start and hopefully it works (there shouldn't be any saved lists anymore)

The more complicated way is going into chromes preferences, there under delete browser data, extended and there should some where be an option to delete app data. But this deletes the data for ALL apps, not just this one.

I hope that fixes it for you. I'm happy someone is even using this little project :)

**Comment by Conan547** [comment]
It seems to be fixed, brilliant!

Thank you so much for making it, DR is an incredible system and it needed this kind of army builder. Only thing I'd add is the ability to make custom rules and unit profiles, but it's already superb.

**Comment by dickloraine** [comment]
Glad it worked for you. Yeah, DR is brilliant, one of my most played systems. Adding custom rules and units would be possible, maybe I implement this if I find the time and a good solution to expose that in a nice UI.
